adamwoodcock98/travel-angel

- README.md
> README amended

- server/controllers/user.js
- server/package.json
- server/routes/user.js
- server/server.js
> Converted to CommonJS

- client/src/components/App.js
- client/src/components/navBar/navBar.js
- client/src/index.js
- package-lock.json
- server/server.js
Navbar component now shown at top of the page, with drop down menu
> Navbar component

- server/routes/user.js
Sorry guys, a little mistake here.
> Fixed a little typo

- server/controllers/flights.js
- server/models/flight.js
- server/spec/models/flight.test.js
Populate and test a flight schema. Pass flight data from the DB into the front end.
> Flight schema

- client/src/components/App.js
- client/src/components/authentication/authentication.js
- client/src/components/authentication/logOut/logOut.js
- client/src/components/navBar/navBar.js
- client/src/index.js
- server/controllers/flights.js
- server/controllers/user.js
- server/package-lock.json
- server/package.json
- server/server.js
Edited sessions to work with the front end
can access the session user id on the front end
> Authentication and sessions working with frontend

- client/src/components/App.js
- client/src/components/dashboard/dashboard.js
Ensure the session is persisted across pages and refreshes
implemented local storage of state
> Added code to persist the session storage across pages

- client/src/components/dashboard/dashboard.js
- server/server.js
> Fixed the server

- client/src/components/dashboard/accommodation/accommodation.js
- client/src/components/dashboard/accommodation/accommodationCard.js
- client/src/components/dashboard/flights/viewFlights/flightCard.js
- client/src/components/dashboard/flights/viewFlights/footerPane.js
- client/src/components/dashboard/parking/parking.js
- client/src/components/dashboard/parking/viewParking.js
> Directions

- client/src/components/dashboard/accommodation/addAccommodation.js
- client/src/components/dashboard/flights/addFlight.js
- client/src/components/dashboard/parking/addParking.js
- client/src/components/dashboard/parking/viewParking/viewParking.js
- client/src/components/dashboard/transfers/addTransfer.js
- client/src/components/dashboard/visas/addVisa.js
- client/src/components/dashboard/visas/visas.js
Dates and times  auto populate when edit a specific card
> Populate dates when editing 

- README.md
> Added resources to the readme

- client/src/components/dashboard/flights/addFlight.js
- client/src/components/dashboard/flights/flights.js
Moved logic over to addflight file
- [] I have created a PR ticket on the [Trello board](https://trello.com/b/P8lEsvZe/acebook).
- [] I will link the PR to the Trello card once created.
> Flight API - fixed

- client/src/components/App.js
- client/src/components/trips/trips.css
- client/src/components/trips/trips.js
- client/src/components/trips/viewTrips/viewTrips.js
> Upcoming trips are in a chronological order + Countdown for the next trip

- client/src/components/dashboard/covid/tests/crud/crud.js
- client/src/components/dashboard/covid/tests/newTest.js
- client/src/components/dashboard/covid/tests/testCard.js
Added uploading and downloading to all routes except COVID
Ability to upload using multer middleware to store files in public folder
Ability to download files
Stopped the infinite rerendering of all
> Covid debugging

- client/src/components/dashboard/dashboard.css
- client/src/components/navBar/navBar.css
- client/src/components/navBar/profile/displayProfile.js
- client/src/components/navBar/profile/profile.css
- client/src/components/trips/trips.css
- client/src/components/trips/trips.js
- client/src/components/trips/viewTrips/viewTrips.css
- client/src/components/trips/viewTrips/viewTrips.js
> CSS CSS CSS

- client/src/components/assets/styling/cards.css
- client/src/components/dashboard/accommodation/accommodation.js
- client/src/components/dashboard/accommodation/accommodationCard.css
- client/src/components/dashboard/accommodation/accommodationCard.js
- client/src/components/dashboard/covid/covid.js
- client/src/components/dashboard/parking/parking.js
- client/src/components/dashboard/transfers/inboundTransferCard.js
- client/src/components/dashboard/transfers/outboundTransferCard.js
- client/src/components/dashboard/transfers/transferCard.css
- client/src/components/dashboard/transfers/transfers.js
- client/src/components/dashboard/visas/viewVisa.css
- client/src/components/dashboard/visas/viewVisa.js
- client/src/components/dashboard/visas/visas.js
Styling cards and other bits and bobs
> Cards styling

- client/src/components/dashboard/parking/addParking.js
- client/src/components/dashboard/parking/viewParking/crud/crud.js
- client/src/components/dashboard/parking/viewParking/viewParking.js
- client/src/components/dashboard/transfers/addTransfer.js
- client/src/components/dashboard/transfers/crud/crud.js
- client/src/components/dashboard/transfers/outboundTransferCard.js
- client/src/components/dashboard/transfers/transfers.js
- client/src/components/dashboard/visas/addVisa.js
- client/src/components/dashboard/visas/crud/crud.js
- client/src/components/dashboard/visas/viewVisa.js
- client/src/components/dashboard/visas/visas.js
Added re-rendering of updates across all components
autofill of forms with date and time fixed
ensure issues with filling dat and time forms
components successfully re-render when needed
> Rerendering

- client/src/components/App.js
- client/src/components/assets/styling/cards.css
- client/src/components/dashboard/accommodation/accommodation.js
- client/src/components/dashboard/covid/covid.css
- client/src/components/dashboard/covid/covid.js
- client/src/components/dashboard/covid/tests/testCard.css
- client/src/components/dashboard/covid/tests/testCard.js
- client/src/components/dashboard/covid/vaccinations/dosePane.js
- client/src/components/dashboard/covid/vaccinations/vaccineCard.css
- client/src/components/dashboard/covid/vaccinations/vaccineCard.js
- client/src/components/dashboard/dashboard.js
- client/src/components/dashboard/flights/flights.js
- client/src/components/dashboard/parking/parking.js
- client/src/components/dashboard/transfers/transfers.js
- client/src/components/dashboard/visas/visas.js
- client/src/components/trips/trips.css
> Bug fixes and improvements

- client/src/components/dashboard/visas/viewVisa.js
removed excess divs
fixes excess div issue
> removed error divs

- README.md
> Included demo video of website
